#!/bin/bash
#
# ouilookup - search for MAC address in IEEE database
# (c) 2018-2019 Vitaly Protsko <villy@sft.ru>
# Licensed under GPLv3
#

if [ -z "$1" ]; then
  echo; echo "Usage: $0 xx[:-]xx[:-]xx[:-xx[:-xx]...] [ xx[:-]xx[:-]xx[:-xx[:-xx]...] ... ]"; echo
  exit 10
fi

while [ -n "$1" ]; do
  item="${1//:/}"
  item="${item//-/}"
  item="${item:0:6}"
  item=$(grep -i "^$item" /usr/share/ieee-data/oui.txt)
  echo "${item/ *}  ${item/*\)		}"

  shift
done

# EOF /usr/bin/ouilookup
